name: Build RPM and DEB packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential rpm devscripts

    - name: Prepare RPM directories
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp scripts/count_files.sh ~/rpmbuild/SOURCES/
        cp specs/count_files.spec ~/rpmbuild/SPECS/

    - name: Build RPM package
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/count_files.spec

    - name: Build DEB package
      run: |
        cd packages
        dpkg-deb --build count-files_1.0-2_amd64.deb
