name: Build RPM and DEB packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential rpm devscripts fakeroot

    - name: Build RPM package
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp $GITHUB_WORKSPACE/specs/count_files.spec ~/rpmbuild/SPECS/
        rpmbuild -ba ~/rpmbuild/SPECS/count_files.spec

    - name: Build DEB package
      run: |
        cd $GITHUB_WORKSPACE/deb-package
        dpkg-buildpackage -us -uc

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: built-packages
        path: |
          ~/rpmbuild/RPMS/x86_64/*.rpm
          ~/rpmbuild/SRPMS/*.src.rpm
          $GITHUB_WORKSPACE/*.deb
